version: '3'

services:
  app:
    image: node:${NODE_VERSION}-alpine
    working_dir: /code
    volumes:
      - .:/code
    ports:
      - ${APP_OUTSIDE_PORT}:${APP_INSIDE_PORT}
      - 9229:9229 # node debug 监听端口

    command: npm config set registry https://registry.npm.taobao.org
    command: npm run start:debug

  # db:
  #   image: mysql:${MYSQL_VERSION}
  #   command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  #   restart: always
  #   ports:
  #     - ${MYSQL_OUTSIDE_PORT}:${MYSQL_INSIDE_PORT}
  #   environment:
  #     MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  #     MYSQL_DATABASE: ${MYSQL_DATABASE}
  #     MYSQL_USER: ${MYSQL_USER}
  #     MYSQL_PASSWORD: ${MYSQL_PASSWORD}
