name: deploy

on:
  push:
    branches:
      - 'main'
    paths:
      - 'manifest/**'
      - 'packages/**'
      - 'presets/**'
      - 'protocol/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16]

    steps:
      - uses: actions/checkout@v2

      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.VRN_REMOTE_SERVER_SSH_PRIVATE_KEY }}
          name: vrn_rsa
          known_hosts: ${{ secrets.VRN_REMOTE_SERVER_SSH_KNOWN_HOSTS }}
          config: ${{ secrets.VRN_REMOTE_SERVER_SSH_CONFIG }}

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.28.0

      - name: Install Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i

      # - name: Testing
      #   run: npm run test

      - name: Run compile and build packages
        run: pnpm build

      - name: Generate manifest and pack boilerplate
        run: pnpm gen:manifest:http

      - name: Deploy
        run: pnpm deploy:ci
        env:
          BOILERPLATE_DEPLOY_DIR: ${{ secrets.BOILERPLATE_DEPLOY_DIR }}
